name: visanka_chat_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  get: 4.6.6
  animated_splash_screen: 1.3.0
  google_fonts: ^6.1.0
  bottom_sheet: 4.0.0
  story: 1.1.0
  sticky_headers: 0.3.0+2
  flutter_sticky_header: 0.6.5
  lottie: 2.7.0
  syncfusion_flutter_datepicker: 23.1.43
  font_awesome_flutter: 10.6.0
  custom_radio_grouped_button: 2.2.1
  roundcheckbox: 2.0.5
  flutter_chat_ui: 1.6.9
  flutter_chat_types: ^3.6.2
  image_picker: 1.0.4
  open_filex: ^4.3.4
  bubble: ^1.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

